### PR TITLE
Add set methods

### LINKED ISSUE #47: Set Component Attributes at Runtime
When working on the counter I example, I noticed it would be useful to change the label of the button outside of the decorator.

```python
row = flare.Row(
    button.set_label("The number is 1").set()
)
```

This should also be done for select menu attributes and other button attributes.

Don't think this is 100% required for version `0.1.0b1`

### PR DESCRIPTION
**Pull request by Lunarmagpie**
This PR also optimizing how cloning works so components created with a decorator are never mutated. Im not sure how to best document this.

closes #47

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
This may be too jank. This code would not work as expected.
```python
@flare.button()
def button:
   ....

a = button.set_label("1234")
b = a.set_label("a")
c = a.set_label("b")

print(a.label)  # b
print(b.label)  # b
print(c.label)  # b
```

**Comment by Lunarmagpie** [comment]
Another solution is requiring a method to be called before any changes to a button. Like `.clone()` or something. This would make it very explicit when a clone is made but it bloats up the API so I would rather clone everything and optimize later with rust/a custom clone function or something.

**Comment by Lunarmagpie** [comment]
Now whenever you mutate everything it clones. Cloning is at least 5x faster than the serializing method so its quite cheap really.

**Review by HyperGH — APPROVED** [review]
Cloning go brrrrr

**Pull request merged**
