### PR TITLE
Improve project metadata

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Improve project metadata

### CODE REVIEW

**Comment by Lunarmagpie** [comment]
This is what it looks like on pypi https://test.pypi.org/project/hikari-flare/0.2.0/

**Review by HyperGH — COMMENTED** [review]
A short description of what the library is and what it is trying to do might be beneficial for the pypi page, although it may be out of scope of this PR.

**Review by HyperGH — APPROVED** [review]

**Comment by Lunarmagpie** [comment]
Do you mean something needs to be added to the README?

**Comment by HyperGH** [comment]
> Do you mean something needs to be added to the README?

For some reason I thought the two were seperate... I'm dumb.

**Pull request merged**
