### PR TITLE
Add link button

### PR DESCRIPTION
**Pull request by Lunarmagpie**
Create link button

Used like `flare.Row(button, flare.LinkButton("google.com", label="Your mom")`

### CODE REVIEW

**Comment by HyperGH** [comment]
Question: Why doesn't a `Component` have a custom_id or cookie? Seems like those should be inherited from there even if it may not have params. Also probably good for future-proofing since these could be used for modal components like TextInputs too.

**Comment by Lunarmagpie** [comment]
There is no cookie since link button components don't have one. I don't think modal components would have one either.
I didn't give it a custom id because I think it would get messy with link buttons wanting a url and everything else wanting a custom id. I can change it so that Link button has that attribute and it's the same as url thought.

**Comment by Lunarmagpie** [comment]
Wondering if we need traits

**Comment by HyperGH** [comment]
> Wondering if we need traits: `Component`, `SupportsCallback`, `SupportsCookie`

Yeah this might be a way. `Component` is the base cls, then we implement seperate traits on the ones that actually have a callback or cookie.

**Comment by Lunarmagpie** [comment]
> Wondering if we need traits: `Component`, `SupportsCallback`, `SupportsCookie`

Done

**Review by HyperGH — APPROVED** [review]

**Pull request merged**
